#!/bin/sh
ERRORS=0
for f in ./$1/*.ferry
do
    echo  $f #${f%.ferry} 
    $2 $3 -f $f > result.txt 
    diff -b result.txt ${f%.ferry}.$4
    ERRORS=$[$ERRORS+$?] 
    rm result.txt
done
exit $ERRORS